version: '3'

services:
  postgres-lireddit:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "thienry"
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
    ports:
      - "15432:5432"
    networks:
      - postgres-compose-network
      
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "thmoura14@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "thienry-dev!"
    ports:
      - "16543:80"
    depends_on:
      - postgres-lireddit
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge